// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

var ActivationPlaceEnum = /* module */[];

var ActionTypeEnum = /* module */[];

var ViewProfileEvent = /* module */[];

var ActionEvent = /* module */[];

var Event = /* module */[];

var EventBody = /* module */[];

var HotpanelProto = /* module */[
  /* ActivationPlaceEnum */ActivationPlaceEnum,
  /* ActionTypeEnum */ActionTypeEnum,
  /* ViewProfileEvent */ViewProfileEvent,
  /* ActionEvent */ActionEvent,
  /* Event */Event,
  /* EventBody */EventBody
];

function eventToEventName($$event) {
  if ($$event) {
    return "EVENT_NAME_VIEW_PROFILE";
  } else {
    return "EVENT_NAME_ACTION";
  }
}

function sendBody(body) {
  var sendableBody = JSON.stringify(body);
  console.log(sendableBody === undefined ? undefined : Js_primitive.some(sendableBody));
  return /* () */0;
}

function track($$event, eventBody) {
  var eventName = $$event ? "EVENT_NAME_VIEW_PROFILE" : "EVENT_NAME_ACTION";
  return sendBody(/* record */[
              /* event */$$event,
              /* body */eventBody,
              /* name */eventName,
              /* ts */Date.now() | 0
            ]);
}

var HotpanelAPI = /* module */[
  /* eventToEventName */eventToEventName,
  /* sendBody */sendBody,
  /* track */track
];

var Hotpanel = /* module */[
  /* ActivationPlaceEnum */ActivationPlaceEnum,
  /* ActionTypeEnum */ActionTypeEnum,
  /* ViewProfileEvent */ViewProfileEvent,
  /* ActionEvent */ActionEvent,
  /* Event */Event,
  /* EventBody */EventBody,
  /* eventToEventName */eventToEventName,
  /* sendBody */sendBody,
  /* track */track
];

var userId = "123456";

track(/* ViewProfileEvent */1, {
      encrypted_user_id: userId,
      activation_place: /* ActivationPlaceDiscover */1
    });

track(/* ActionEvent */0, {
      action_type: /* ActivationTypeClick */0
    });

exports.HotpanelProto = HotpanelProto;
exports.HotpanelAPI = HotpanelAPI;
exports.Hotpanel = Hotpanel;
exports.userId = userId;
/*  Not a pure module */
