// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Js_math = require("bs-platform/lib/js/js_math.js");

var ActivationPlaceEnum = /* module */[];

var ActionTypeEnum = /* module */[];

var ViewProfileEvent = /* module */[];

function trackViewProfileEvent($$event) {
  var match = $$event[/* encrypted_user_id */0];
  if (match !== undefined) {
    console.log(match + "as");
    return /* () */0;
  } else {
    return /* () */0;
  }
}

function getUserId(param) {
  return String(Js_math.floor(Math.random() * 100000.0));
}

var userId = getUserId(/* () */0);

trackViewProfileEvent(/* record */[
      /* encrypted_user_id */userId,
      /* activation_place *//* ActivationPlaceDiscover */1
    ]);

trackViewProfileEvent(/* record */[
      /* encrypted_user_id */userId,
      /* activation_place */undefined
    ]);

trackViewProfileEvent(/* record */[
      /* encrypted_user_id */userId,
      /* activation_place */undefined
    ]);

exports.ActivationPlaceEnum = ActivationPlaceEnum;
exports.ActionTypeEnum = ActionTypeEnum;
exports.ViewProfileEvent = ViewProfileEvent;
exports.trackViewProfileEvent = trackViewProfileEvent;
exports.getUserId = getUserId;
exports.userId = userId;
/* userId Not a pure module */
