// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Js_math = require("bs-platform/lib/js/js_math.js");

var ActivationPlaceEnum = /* module */[];

var ActionTypeEnum = /* module */[];

var ViewProfileEvent = /* module */[];

function trackViewProfileEvent($$event) {
  var match = $$event.activation_place;
  if (match !== undefined) {
    var match$1 = $$event.encrypted_user_id;
    if (match$1 !== undefined) {
      console.log(match$1 + "as");
      return /* () */0;
    } else {
      return /* () */0;
    }
  } else {
    return /* () */0;
  }
}

function getUserId(param) {
  return String(Js_math.floor(Math.random() * 100000.0));
}

var userId = getUserId(/* () */0);

trackViewProfileEvent({
      encrypted_user_id: userId,
      activation_place: /* ActivationPlaceDiscover */1
    });

exports.ActivationPlaceEnum = ActivationPlaceEnum;
exports.ActionTypeEnum = ActionTypeEnum;
exports.ViewProfileEvent = ViewProfileEvent;
exports.trackViewProfileEvent = trackViewProfileEvent;
exports.getUserId = getUserId;
exports.userId = userId;
/* userId Not a pure module */
