/* TypeScript file generated by genType. */

// tslint:disable-next-line:no-var-requires
const HotpanelAPITSBS = require('./HotpanelAPITS.bs');

import {Event_t as HotpanelProtoTS_Event_t} from './HotpanelProtoTS.gen';

export const track: (_1:HotpanelProtoTS_Event_t) => void = HotpanelAPITSBS.track;
