// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var HotpanelAPI = require("../example/HotpanelAPI.bs.js");
var HotpanelProto = require("../example/HotpanelProto.bs.js");

var ActivationPlaceEnum = HotpanelProto.ActivationPlaceEnum;

var ActionTypeEnum = HotpanelProto.ActionTypeEnum;

var ViewProfileEvent = HotpanelProto.ViewProfileEvent;

var ActionEvent = HotpanelProto.ActionEvent;

var Event = HotpanelProto.Event;

var EventBody = HotpanelProto.EventBody;

var eventToEventName = HotpanelAPI.eventToEventName;

var stringifyEventBody = HotpanelAPI.stringifyEventBody;

var sendBody = HotpanelAPI.sendBody;

var track = HotpanelAPI.track;

exports.ActivationPlaceEnum = ActivationPlaceEnum;
exports.ActionTypeEnum = ActionTypeEnum;
exports.ViewProfileEvent = ViewProfileEvent;
exports.ActionEvent = ActionEvent;
exports.Event = Event;
exports.EventBody = EventBody;
exports.eventToEventName = eventToEventName;
exports.stringifyEventBody = stringifyEventBody;
exports.sendBody = sendBody;
exports.track = track;
/* No side effect */
