// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var HotpanelAPI = require("./HotpanelAPI.bs.js");
var HotpanelProto = require("./HotpanelProto.bs.js");

var ActivationPlaceEnum = HotpanelProto.ActivationPlaceEnum;

var ActionTypeEnum = HotpanelProto.ActionTypeEnum;

var ViewProfileEvent = HotpanelProto.ViewProfileEvent;

var ActionEvent = HotpanelProto.ActionEvent;

var Event = HotpanelProto.Event;

var EventBody = HotpanelProto.EventBody;

var track = HotpanelAPI.track;

exports.ActivationPlaceEnum = ActivationPlaceEnum;
exports.ActionTypeEnum = ActionTypeEnum;
exports.ViewProfileEvent = ViewProfileEvent;
exports.ActionEvent = ActionEvent;
exports.Event = Event;
exports.EventBody = EventBody;
exports.track = track;
/* No side effect */
