// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function track($$event) {
  var body = JSON.stringify($$event[0]);
  console.log(body === undefined ? undefined : Js_primitive.some(body));
  return /* () */0;
}

exports.track = track;
/* No side effect */
