// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';


var ActivationPlaceEnum = /* module */[];

var ActionTypeEnum = /* module */[];

var ViewProfileEvent = /* module */[];

var ActionEvent = /* module */[];

var Event = /* module */[];

var EventBody = /* module */[];

exports.ActivationPlaceEnum = ActivationPlaceEnum;
exports.ActionTypeEnum = ActionTypeEnum;
exports.ViewProfileEvent = ViewProfileEvent;
exports.ActionEvent = ActionEvent;
exports.Event = Event;
exports.EventBody = EventBody;
/* No side effect */
