// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Hotpanel = require("./Hotpanel.bs.js");

var userId = "123456";

Hotpanel.track(/* ViewProfileEvent */Block.__(1, [{
          encrypted_user_id: userId,
          activation_place: /* ActivationPlaceDiscover */1
        }]));

Hotpanel.track(/* ActionEvent */Block.__(0, [{
          action_type: /* ActivationTypeClick */0
        }]));

exports.userId = userId;
/*  Not a pure module */
